-- ============================================================
--  Hi Solar Job Tracker — Supabase Database Setup
--  วิธีใช้: เปิด Supabase Dashboard → SQL Editor → วาง + Run
-- ============================================================

-- ── 1. ดูงาน (Site Visits) ────────────────────────────────
create table if not exists du_ngan (
  id          bigint generated by default as identity primary key,
  date        text,
  time        text,
  customer    text not null,
  phone       text,
  maps_url    text,
  note        text,
  status      text default 'รอดูงาน',
  updated_by  text,
  created_at  timestamptz default now(),
  updated_at  timestamptz default now()
);

-- ── 2. งาน (Jobs) ─────────────────────────────────────────
create table if not exists ngan (
  id           bigint generated by default as identity primary key,
  created_date text,
  customer     text not null,
  phone        text,
  detail       text,
  maps_url     text,
  type         text,
  technician   text,
  price        numeric,
  status       text default 'Waiting',
  note         text,
  updated_by   text,
  created_at   timestamptz default now(),
  updated_at   timestamptz default now()
);

-- ── 3. ล้างแผง (Panel Cleaning) ───────────────────────────
create table if not exists lang_paeng (
  id               bigint generated by default as identity primary key,
  customer         text not null,
  maps_url         text,
  appointment_date text,
  technician       text,
  status           text default 'รอนัด',
  note             text,
  updated_by       text,
  created_at       timestamptz default now(),
  updated_at       timestamptz default now()
);

-- ── 4. ซ่อม (Repair) ──────────────────────────────────────
create table if not exists som (
  id            bigint generated by default as identity primary key,
  item          text not null,
  customer      text,
  sent_date     text,
  received_date text,
  status        text default 'รอส่ง',
  note          text,
  updated_by    text,
  created_at    timestamptz default now(),
  updated_at    timestamptz default now()
);

-- ── 5. บิล VAT (Billing) ──────────────────────────────────
create table if not exists bil (
  id         bigint generated by default as identity primary key,
  customer   text not null,
  amount     numeric,
  date       text,
  status     text default 'รอออกบิล',
  note       text,
  updated_by text,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

-- ── RLS Policies (เปิดให้ anon key อ่าน-เขียนได้ = ทีมงาน) ─
alter table du_ngan   enable row level security;
alter table ngan      enable row level security;
alter table lang_paeng enable row level security;
alter table som       enable row level security;
alter table bil       enable row level security;

create policy "team_all" on du_ngan    for all to anon using (true) with check (true);
create policy "team_all" on ngan       for all to anon using (true) with check (true);
create policy "team_all" on lang_paeng for all to anon using (true) with check (true);
create policy "team_all" on som        for all to anon using (true) with check (true);
create policy "team_all" on bil        for all to anon using (true) with check (true);

-- ── Seed Data (ข้อมูลจาก 00 Hi Solar Planner.txt) ────────

-- ดูงาน
insert into du_ngan (date, time, customer, phone, maps_url, note, status) values
  ('02/04/2026', '10:00', 'บ้านคุณเต็มดวง สันป่าตอง',     '',             'https://maps.app.goo.gl/VWdaUybNycs852yX8', '',                                          'รอดูงาน'),
  ('02/04/2026', '13:30', 'บ้านสวนสันทราย',                '',             'https://maps.app.goo.gl/mhC6TzXETE1ruEFD8', '',                                          'รอดูงาน'),
  ('03/04/2026', '10:00', 'Rich Atlas ใกล้ Big C หางดง',   '',             'https://maps.app.goo.gl/L8ih7LuvGhUWiziT7', '',                                          'รอดูงาน'),
  ('03/04/2026', '13:00', 'วราภรณ์ (Lucky)',               '0807902365',   'https://maps.app.goo.gl/XYudYMX5aeSBrHV56', '',                                          'รอดูงาน'),
  ('04/04/2026', '',      'คุณปู — หมู่บ้านกุลพันธ์',     '',             '',                                           '',                                          'รอดูงาน'),
  ('09/04/2026', '10:30', 'บ้านคุณทับทิม',                '',             'https://maps.app.goo.gl/a6weVtWVX4pD1ozp9', 'แนะนำโดย ผรม.คุณเก่ง | 10KW Hybrid 3 Phase','รอดูงาน'),
  ('16/04/2026', '',      'เพื่อนคุณ LINDA — Upgrade ระบบ','',            '',                                           '',                                          'รอดูงาน');

-- งาน
insert into ngan (created_date, customer, detail, maps_url, type, price, status) values
  ('07/04/2026', 'คุณ Tap — กาญจนกนก 19 (Sorawit home)', 'ล้างแผง / ตะแกรงกันนก',                             'https://maps.app.goo.gl/mQukt7wCLHAXw2uv8', '',         null,  'Done'),
  ('',           'คุณเอ๋นุชชนาท — ดอยสะเก็ด',            'ติดตั้งแบตเตอรี่ FLA48250 + แผงกันหมาฉี่',          'https://maps.app.goo.gl/mqKgBRN3Js6mdfQ68', 'Off Grid', null,  'Waiting'),
  ('',           'สวนแม่วาง',                             'ย้ายระบบ Off Grid จากสวน → ตัวเมืองแม่วาง',         'https://maps.app.goo.gl/iSQHvhTMsQRyVnPG6', 'Off Grid', null,  'Waiting'),
  ('',           'คุณลินดา',                              'เพิ่มแบตเตอรี่ LV Topsun',                          '',                                           '',         null,  'Waiting'),
  ('',           'คุณหมอวีระชาติ',                        'เพิ่มแบตเตอรี่ PSI',                                '',                                           '',         null,  'Waiting'),
  ('',           'คุณปู — หมู่บ้านกุลพันธ์ 19',           'ติดตั้งแผง 8 ใบ (465W→670W) + เปลี่ยน CT',         '',                                           'Hybrid',   45000, 'Waiting'),
  ('',           'คุณเต็มดวง — สันป่าตอง',               'เพิ่มแผง (จากบ้านคุณปู) + ติดตั้ง CT จุดใหม่',    '',                                           '',         25000, 'Waiting'),
  ('',           'คุณอุ๋ย',                               'ปรับปรุงระบบ',                                       '',                                           '',         null,  'Waiting');

-- ล้างแผง
insert into lang_paeng (customer, maps_url, status) values
  ('บ้านคุณ Nook Home', 'https://maps.app.goo.gl/Z4f3XEq5RHHNbAPf7', 'รอนัด');

-- ซ่อม
insert into som (item, customer, status, note) values
  ('Inverter', 'หอพักสุธาสินี', 'ส่งซ่อมแล้ว', 'เครื่องมีปัญหาภายใน');

-- บิล
insert into bil (customer, amount, status) values
  ('เสาวรภย์ กุสุมา ณ อยุธยา',                      250000,  'รอออกบิล'),
  ('คุณอุรพันธ์ สุขสมนิตย์',                         210000,  'รอออกบิล'),
  ('บริษัท ราชาน๊อต จำกัด',                          489000,  'รอออกบิล'),
  ('บริษัท แพทริค แมค ไบรด์ มาร์เก็ตติ้ง จำกัด',   1060000, 'รอออกบิล');
